config/routes.rb
Rails.application.routes.draw do
  get 'sample2' => 'sample2#index'
  get 'sample1' => 'sample1#index'
  get 'home' => 'home#index'

  resources :days
  resources :fees
  resources :addresses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :fee
  has_many :day, primary_key: 'state', foreign_key: 'state'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :address, primary_key: 'state', foreign_key: 'state'
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :address
  belongs_to :addr, class_name: 'Address', foreign_key: 'address_id'
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:state)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.all
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render :new }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:state, :transportation, :day)
    end
end

app/controllers/fees_controller.rb
class FeesController < ApplicationController
  before_action :set_fee, only: [:show, :edit, :update, :destroy]

  # GET /fees
  # GET /fees.json
  def index
    @fees = Fee.all
  end

  # GET /fees/1
  # GET /fees/1.json
  def show
  end

  # GET /fees/new
  def new
    @fee = Fee.new
  end

  # GET /fees/1/edit
  def edit
  end

  # POST /fees
  # POST /fees.json
  def create
    @fee = Fee.new(fee_params)

    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee, notice: 'Fee was successfully created.' }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fees/1
  # PATCH/PUT /fees/1.json
  def update
    respond_to do |format|
      if @fee.update(fee_params)
        format.html { redirect_to @fee, notice: 'Fee was successfully updated.' }
        format.json { render :show, status: :ok, location: @fee }
      else
        format.html { render :edit }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fees/1
  # DELETE /fees/1.json
  def destroy
    @fee.destroy
    respond_to do |format|
      format.html { redirect_to fees_url, notice: 'Fee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fee
      @fee = Fee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fee_params
      params.require(:fee).permit(:address_id, :fee)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sample1_controller.rb
class Sample1Controller < ApplicationController
  def index

    @addresses = Address.all
    @fees = Fee.all
    @days = Day.all

    ##
    # Fee
    # join : fee(address_id) - address(id)
    #

    # 基本的なjoin
    @join1 = Fee.joins(:address).where("addresses.state = 'tokyo'")

    # 別名でのjoin
    @join2 = Fee.joins(:addr).where("addresses.state = 'tokyo'")

    # find_byは使えない
    #Fee.joins(:address).find_by(state: 'osaka')


    ##
    # Fee
    # join : dat(status) - address(status)
    #

    # 基本的なjoin
    @join3 = Day.joins(:address).where("addresses.state = 'tokyo'")

    # 親のカラム名も取得したい場合
    @join4 = Day.joins(:address).select("addresses.*, days.*").where("addresses.state = 'tokyo'")

    # find_byは使えない
    #Day.joins(:address).find_by(addresses.id : 2)

  end
end

app/controllers/sample2_controller.rb
class Sample2Controller < ApplicationController
  def index

    @addresses = Address.all
    @fees = Fee.all

    ##
    # n+1問題
    #
    puts '>>> NGパターン'

    fees = Fee.all
    fees.each do |f|
      f.address.state
    end

    puts '>>> OKパターン'

    fees = Fee.all.includes(:address)
    fees.each do |f|
      f.address.state
    end

  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/fees_helper.rb
module FeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sample1_helper.rb
module Sample1Helper
end

app/helpers/sample2_helper.rb
module Sample2Helper
end

app/views/addresses/_form.html.erb
<%= form_for(address) do |f| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.state %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/days/_form.html.erb
<%= form_for(day) do |f| %>
  <% if day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :transportation %>
    <%= f.text_field :transportation %>
  </div>

  <div class="field">
    <%= f.label :day %>
    <%= f.text_field :day %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Days</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Transportation</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.state %></td>
        <td><%= day.transportation %></td>
        <td><%= day.day %></td>
        <td><%= link_to 'Show', day %></td>
        <td><%= link_to 'Edit', edit_day_path(day) %></td>
        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @day.state %>
</p>

<p>
  <strong>Transportation:</strong>
  <%= @day.transportation %>
</p>

<p>
  <strong>Day:</strong>
  <%= @day.day %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>

app/views/fees/_form.html.erb
<%= form_for(fee) do |f| %>
  <% if fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fee.errors.count, "error") %> prohibited this fee from being saved:</h2>

      <ul>
      <% fee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address_id %>
    <%= f.text_field :address_id %>
  </div>

  <div class="field">
    <%= f.label :fee %>
    <%= f.text_field :fee %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fees/edit.html.erb
<h1>Editing Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Show', @fee %> |
<%= link_to 'Back', fees_path %>

app/views/fees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fees</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fees.each do |fee| %>
      <tr>
        <td><%= fee.address_id %></td>
        <td><%= fee.fee %></td>
        <td><%= link_to 'Show', fee %></td>
        <td><%= link_to 'Edit', edit_fee_path(fee) %></td>
        <td><%= link_to 'Destroy', fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fee', new_fee_path %>

app/views/fees/new.html.erb
<h1>New Fee</h1>

<%= render 'form', fee: @fee %>

<%= link_to 'Back', fees_path %>

app/views/fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @fee.address_id %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @fee.fee %>
</p>

<%= link_to 'Edit', edit_fee_path(@fee) %> |
<%= link_to 'Back', fees_path %>

app/views/home/index.html.erb
<h1>ActiveRecord Sample</h1>

<hr>

<%=	link_to 'sample: join', sample1_path  %>
<br>
<%=	link_to 'sample: N+1問題', sample2_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBasesApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sample1/index.html.erb
<h1>join</h1>

<hr>

<h3>テーブル</h3>

<%= image_tag 'sample1.png' %>

<br>

<%= link_to 'address', addresses_path %>

<table border="1">
  <tr>
    <th>id</th>
    <th>state</th>
  </tr>
  <% @addresses.each do |a| %>
      <tr>
        <td><%= a.id %></td>
        <td><%= a.state %></td>
      </tr>
  <% end %>
</table>

<br>

<%= link_to 'fee', fees_path %>

<table border="1">
  <tr>
    <th>id</th>
    <th>fee</th>
    <th>address_id</th>
  </tr>
  <% @fees.each do |f| %>
      <tr>
        <td><%= f.id %></td>
        <td><%= f.fee %></td>
        <td><%= f.address_id %></td>
      </tr>
  <% end %>
</table>

<br>

<%= link_to 'day', days_path %>

<table border="1">
  <tr>
    <th>id</th>
    <th>state</th>
    <th>transportation</th>
    <th>day</th>
  </tr>
  <% @days.each do |d| %>
      <tr>
        <td><%= d.id %></td>
        <td><%= d.state %></td>
        <td><%= d.transportation %></td>
        <td><%= d.day %></td>
      </tr>
  <% end %>
</table>

<hr>

<h3>親の「主キー」と子の「親名_id」カラムで関連付ける</h3>

<div class="module_code">model: address</div>
<pre class="prettyprint">has_one :fee</pre>

<div class="module_code">model: fee</div>
<pre class="prettyprint">belongs_to :address</pre>

<div class="module_code">controller: 基本的なjoin</div>
<pre class="prettyprint">
Fee.joins(:address).where("addresses.state = 'tokyo'")
=>
<%= @join1.inspect %>
</pre>

<hr>

<h3>親の「主キー」と子の「親名_id」カラムで関連付けるが、別名でjoinさせる</h3>

<div class="module_code">model: address</div>
<pre class="prettyprint">has_one :fee</pre>

<div class="module_code">model: fee</div>
<pre class="prettyprint">belongs_to :addr, class_name: 'Address', foreign_key: 'address_id'</pre>

<div class="module_code">controller: 別名でのjoin</div>
<pre class="prettyprint">
Fee.joins(:addr).where("addresses.state = 'tokyo'")
=>
<%= @join2.inspect %>
</pre>

<hr>

<h3>親と子で共通するカラム同士で関連付ける</h3>

<div class="module_code">model: address</div>
<pre class="prettyprint">has_many :day, primary_key: 'state', foreign_key: 'state'</pre>

<div class="module_code">model: day</div>
<pre class="prettyprint">belongs_to :address, primary_key: 'state', foreign_key: 'state'</pre>

<div class="module_code">controller: 基本的なjoin</div>
<pre class="prettyprint">
Day.joins(:address).where("addresses.state = 'tokyo'")
=>
<%= @join3.inspect %>
</pre>

<hr>

<h3>補足</h3>

<div class="module_code">controller: 親のカラムも取得したい場合</div>
<pre class="prettyprint">
Day.joins(:address).select("addresses.*, days.*").where("addresses.state = 'tokyo'")
=>
<%= @join4.inspect %>
</pre>

app/views/sample2/index.html.erb
<h1>N+1問題</h1>

<hr>

<h3>テーブル</h3>

<%= image_tag 'sample1.png' %>

<br>

<%= link_to 'address', addresses_path %>

<table border="1">
  <tr>
    <th>id</th>
    <th>state</th>
  </tr>
  <% @addresses.each do |a| %>
      <tr>
        <td><%= a.id %></td>
        <td><%= a.state %></td>
      </tr>
  <% end %>
</table>

<br>

<%= link_to 'fee', fees_path %>

<table border="1">
  <tr>
    <th>id</th>
    <th>fee</th>
    <th>address_id</th>
  </tr>
  <% @fees.each do |f| %>
      <tr>
        <td><%= f.id %></td>
        <td><%= f.fee %></td>
        <td><%= f.address_id %></td>
      </tr>
  <% end %>
</table>

<hr>

<h3>N+1問題が発生するクエリ</h3>

<div class="module_code">ループ＋１回のクエリが発行される</div>
<pre class="prettyprint">
fees = Fee.all
fees.each do |f|
  f.address.state
end
=>
  Fee Load (0.3ms)  SELECT "fees".* FROM "fees"
  Address Load (0.1ms)  SELECT  "addresses".* FROM "addresses" WHERE "addresses"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Address Load (0.1ms)  SELECT  "addresses".* FROM "addresses" WHERE "addresses"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  Address Load (0.1ms)  SELECT  "addresses".* FROM "addresses" WHERE "addresses"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
  Address Load (0.1ms)  SELECT  "addresses".* FROM "addresses" WHERE "addresses"."id" = ? LIMIT ?  [["id", 4], ["LIMIT", 1]]
  ...
</pre>

<hr>

<h3>N+1問題が発生しないクエリ</h3>

<div class="module_code">２つのクエリだけ発行される</div>
<pre class="prettyprint">
fees = Fee.all.includes(:address)
fees.each do |f|
  f.address.state
end
=>
  CACHE (0.0ms)  SELECT "fees".* FROM "fees"
  Address Load (0.2ms)  SELECT "addresses".* FROM "addresses" WHERE "addresses"."id" IN (1, 2, 3,4)
</pre>